name: imei_generator
description: Generates IMEI number and validates any given IMEI number
version: 1.0.0
# homepage: https://www.example.com
repository: https://github.com/ZahidTekbas/imei_generator

environment:
  sdk: '>=2.18.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
